set(CMAKE_C_COMPILER   "gcc-wrapper.sh" CACHE PATH "")
set(CMAKE_CXX_COMPILER "g++-wrapper.sh" CACHE PATH "")
set(CMAKE_CUDA_COMPILER "nvcc-wrapper.sh" CACHE PATH "")

set(CMAKE_CXX_FLAGS "" CACHE STRING "")
set(CMAKE_CXX_FLAGS_RELEASE "-O3 -ffast-math -g" CACHE STRING "")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-O3 -g" CACHE STRING "")
set(CMAKE_CXX_FLAGS_DEBUG "-O0 -g" CACHE STRING "")

set(ENABLE_CHAI On CACHE BOOL "")
set(ENABLE_CUDA On CACHE BOOL "")
set(ENABLE_OPENMP Off CACHE BOOL "")
set(ENABLE_MPI On CACHE BOOL "")

set(RAJA_ENABLE_EXERCISES Off CACHE BOOL "")

set(CMAKE_CUDA_ARCHITECTURES "70" CACHE STRING "")
set(CMAKE_CUDA_FLAGS "-restrict -gencode=arch=compute_70,code=sm_70 --extended-lambda" CACHE STRING "")
set(CMAKE_CUDA_FLAGS_RELEASE "-O3 -lineinfo" CACHE STRING "")
set(CMAKE_CUDA_FLAGS_RELWITHDEBINFO "-O3 -lineinfo" CACHE STRING "")
set(CMAKE_CUDA_FLAGS_DEBUG "-O0 -g -G" CACHE STRING "")
set(CMAKE_CUDA_HOST_COMPILER "gcc" CACHE STRING "")


