set(CMAKE_C_COMPILER   "gcc-wrapper.sh" CACHE PATH "")
set(CMAKE_CXX_COMPILER "g++-wrapper.sh" CACHE PATH "")

set(CMAKE_CXX_FLAGS "" CACHE STRING "")
set(CMAKE_CXX_FLAGS_RELEASE "-O3 -mavx -ffast-math -g" CACHE STRING "")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "-O3 -g -mavx" CACHE STRING "")
set(CMAKE_CXX_FLAGS_DEBUG "-O0 -g" CACHE STRING "")

set(ENABLE_OPENMP On CACHE BOOL "")
set(ENABLE_MPI On CACHE BOOL "")

set(RAJA_ENABLE_EXERCISES Off CACHE BOOL "")
